# Generated by Django 4.0.4 on 2022-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(max_length=100),
        ),
    ]
