# Generated by Django 4.0.4 on 2022-07-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_fandoms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fandoms',
            new_name='Fandom',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Review Date')),
                ('review', models.CharField(choices=[('A', 'Great'), ('B', 'Okay'), ('C', 'Not my favorite')], default='A', max_length=1, verbose_name='Review')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
