# Generated by Django 4.0.4 on 2022-07-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_fandoms_fandom_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fandom',
            field=models.ManyToManyField(to='main_app.fandom'),
        ),
    ]
